### ISSUE TITLE
How to load driver from my own signed driver

### ISSUE THREAD

**Issue by eix128** [hfiref0x/KDU#1]
Hi  ,
We got EV Code Signing CERT for Anti cheat.
But our timestamp will be out of date.
We dont want to make payment.We want to embed sys loader inside our own Anti Cheat Driver.
So we will bypass this signature forcement and we will update our own driver
Is there any ready function for that ?
Thanks

**Comment by hfiref0x** [comment]
This post has nothing to do with this repository. Closed as offtopic.
