### ISSUE TITLE
bad image

### ISSUE THREAD

**Issue by tafa45** [hfiref0x/KDU#103]
Please help me. Every time I try to map a driver, I get this error 
![image](https://github.com/user-attachments/assets/cc99156a-4029-414b-8af9-61c5791872d3)

**Comment by hfiref0x** [comment]
Show me this file. I cannot analyze files through screenshots.

**Comment by tafa45** [comment]
what file kdu or the sys im to map

**Comment by tafa45** [comment]
![image](https://github.com/user-attachments/assets/c9e1075a-1ad9-4fff-b45e-dc14756ffa20)

**Comment by tafa45** [comment]
![image](https://github.com/user-attachments/assets/071a87f1-c81b-4126-8e4e-9180f42a8cb2)

**Comment by tafa45** [comment]
![image](https://github.com/user-attachments/assets/5340278c-28b0-4c8c-89c6-604af8b17307)

**Comment by hfiref0x** [comment]
dowtore3rax.sys what is it. I don't need unrelated screnshots, show me the file.

**Comment by tafa45** [comment]
The application it's art money its Like cheat engine

**Comment by tafa45** [comment]
![image](https://github.com/user-attachments/assets/07863823-36ee-486a-b781-3bd7e57c16e1)

**Comment by hfiref0x** [comment]
artmoney driver is 32 bit file. You cannot load 32 bit drivers on 64 bit Windows.

**Comment by tafa45** [comment]
okay it's 32 but I tried a 64 bit and still the same error

**Comment by hfiref0x** [comment]
Which one error it gives you with 64 bit file.

**Comment by hfiref0x** [comment]
Which one error it gives you with 64 bit file.

**Comment by tafa45** [comment]
Bad image And also this
![image](https://github.com/user-attachments/assets/04f5084f-061f-488e-91f8-df6da742e59b)

**Comment by tafa45** [comment]
I can't even map wind64

**Comment by hfiref0x** [comment]
What is wind64 and when I will have the files you are talking about. One more screenshot from you and this entire issue will go to the trashcan.
