### ISSUE TITLE
BSOD in [KDU PATH] -prv 6 -map [MY DRIVER PATH]

### ISSUE THREAD

**Issue by wendy-yeohaengja** [hfiref0x/KDU#104]
hello , and thank you for your project.
my driver cannot map by kdu.
BSOD crash when dropped driver to kdu.
Summary of crash dump points:
Error:
SYSTEM_THREAD_EXCEPTION_NOT_HANDLED (7E)

Exception code:
Access violation 0xC0000005, thread wrote to invalid memory address 00000000000000068

Fault address:
ffffc80bff9f00e9

Module information:
BTHport.sys checksum mismatch

but i cant understand these errors.
i can show you my driver binary file.
please help me 😥

finally , thank you for read my issue

**Comment by hfiref0x** [comment]
Hello, 

What is your driver and how it compiled.

**Comment by wendy-yeohaengja** [comment]
https://drive.google.com/file/d/1Mxa9-gS53KpUgeN4ET7BVrmh3slAI2S6/view?usp=sharing
this is the driver.
please send me the permission request of show the file 😫

**Comment by hfiref0x** [comment]
I don't have google acc :\

**Comment by wendy-yeohaengja** [comment]
oops
but i hate open driver file to public , can i have your discord id?

**Comment by hfiref0x** [comment]
Use this email vampirebaron[at]gmail.com

**Comment by wendy-yeohaengja** [comment]
i sent message 1h ago
sorry for late notisfy

**Comment by hfiref0x** [comment]
You are using the DriverObject parameter in DriverEntry. In manually mapped drivers, DriverEntry parameters are uninitialized garbage - thus, accessing this memory will trigger a bug check.

**Comment by hfiref0x** [comment]
You are using the DriverObject parameter in DriverEntry. In manually mapped drivers, DriverEntry parameters are uninitialized garbage - thus, accessing this memory will trigger a bug check.

**Comment by wendy-yeohaengja** [comment]
i understand.
but i think IOCTL driver cannot create without DriverObject.
how do you think?
please tell me your think 😔

**Comment by hfiref0x** [comment]
Try 
kdu -prv 6 -scv 3 -drvn your_driver_object_name -drvr your_driver_registry_key_name -map path_to_your_driver

e.g
kdu -prv 6 -scv 3 -drvn mycheatobj -drvr mycheat -map c:\hacks\mycheat.sys

And do not use SEH, it won't work in driver mapped by KDU.

If this doesn't work switch to other um<->km communication methods.

**Comment by wendy-yeohaengja** [comment]
sorry
what is SEH?
im noobie sorry 😥

**Comment by hfiref0x** [comment]
If you are not acquainted with Structured Exception Handling, perhaps delving into drivers and kernel mode hacks is not advisable?

**Comment by wendy-yeohaengja** [comment]
yah
I understand now.
finally, I will change communication method (IOCTL -> kernel hook)
