### ISSUE TITLE
[Support] Bad image format when trying to map a driver

### ISSUE THREAD

**Issue by archie426** [hfiref0x/KDU#11]
Hi,
Whenever I try to map a driver, I get a bad image format exception. I've tried with two I've compiled on my home system now. I have sign task off and when I register them as a service using your DSE disable function they load normally. Do I need to enable some other compile-time switch to fit the "driverless" protocol?
Thanks

**Comment by hfiref0x** [comment]
Hello,
what is your compile/linker settings.

**Comment by archie426** [comment]
Sorry for wasting your time, it appeared there was a switch which changed the target architecture in the linker settings, although I had the build config on x64 mode. 

![image](https://user-images.githubusercontent.com/13406648/134533044-e8fee235-240f-4da4-834e-fb829457590d.png)

However, now I get an error that it could not load the drivers database? I've tried on NalDrv and RTCore64 and get the same issue.
