### ISSUE TITLE
Use WskRegister will definitely BSOD

### ISSUE THREAD

**Issue by xxTree** [hfiref0x/KDU#14]
WSK_REGISTRATION     WskRegistration;
 WSK_CLIENT_DISPATCH  WskDispatch = { MAKE_WSK_VERSION(1,0), 0, NULL };

 WSK_CLIENT_NPI WskClient;
 WskClient.ClientContext = NULL;
 WskClient.Dispatch = &WskDispatch;

 WskRegister(&WskClient, &WskRegistration);

I do not know why。。。

**Comment by hfiref0x** [comment]
This is not a KDU issue. KDU is a driver loader, after your driver loaded - KDU work is done. Anything above that is not a subject of questions here.
