### ISSUE TITLE
Error (0xC0000428) on x64

### ISSUE THREAD

**Issue by matheuspaalma** [hfiref0x/KDU#17]
I'm getting this error when trying to load my driver, is this any known?

![64x error](https://user-images.githubusercontent.com/56232936/140543302-6b078c94-0a45-4f37-8856-99900ef9030d.png)

**Comment by matheuspaalma** [comment]
Error 0xC0000428 resolved, all generated dlls need to be in the same directory.

However, when running I am getting blue screen (KMODE_EXCEPTION_HANDLED)

Is this a system error or can it be fixed in the KDU?

**Comment by hfiref0x** [comment]
There are example of acceptable drivers available with full source and and project settings. They are in https://github.com/hfiref0x/KDU/tree/master/Source/Examples, DummyDrv, DummyDrv2. None of them has this flag set for an obvious reasons. You are mapping your driver as code in kernel memory without involving Windows loader. So why then your project has this DSE exclusive setting on? What was the point of it?

When you ask anything about BSOD I (and everybody else) will ask for:
- crash dump
- if you can't provide it for a some reason then at least post your own analysis of it through windbg!analyze -v. No one can translate crash name into actual bug/or place where it happens - this is impossible and most of the time BSOD names are irrelevant and making zero sense. Telepaths also on a vacation.

However judging on your first error with with settings it is likely the same origin too and what you compiled is incompatible with the way KDU maps code into kernel. I suggest you recreate your project configuration using DummyDrv's as base for settings.
