### ISSUE TITLE
BSOD KMODE_EXEPTION_NOT_HANDLED

### ISSUE THREAD

**Issue by matrixhax** [hfiref0x/KDU#20]
Hello 
i got  BSOD KMODE_EXEPTION_NOT_HANDLED
when i -map my driver 
driver dont have any params and unload driver set to NULL
what is issue
thank you

**Comment by hfiref0x** [comment]
Upload your minidump somewhere so I can take a look.

**Comment by hfiref0x** [comment]
No dump - not an issue. Closed.
