### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by desconection** [hfiref0x/KDU#31]
![Screenshot_78](https://user-images.githubusercontent.com/42445392/191862186-ba2818df-a13d-4151-b9fa-e526f8534182.png)

**Comment by hfiref0x** [comment]
Shit happens. Switch to another provider.

**Comment by desconection** [comment]
> Shit happens. Switch to another provider.

i tested provider 0, provider 3, provider 22 and provider 23

**Comment by hfiref0x** [comment]
Run kdu -diag and post results here
