### ISSUE TITLE
Unable to re-enable DSE

### ISSUE THREAD

**Issue by NightfallChease** [hfiref0x/KDU#32]
I have typed the following cmd in the my console "kdu.exe" -prv 1 -dse 6". 
After reentering the same command again (6 replaced with 0)
I was not able to restart my computer without dse dsiabled... I have no clue how to reenable dse because all the methods i've used (bcdedit.exe /set nointegritychecks off  &  troubleshoot restart and enable dse) don't work. Any ideas?

**Comment by hfiref0x** [comment]
You did opposite. First command sets default set of flags into DSE value. Second command you have typed - zeroed all flags, disabling DSE.

**Comment by NightfallChease** [comment]
Oh yeah, I didn't even noticed that... My system still boots with DSE disabled by default after using KDU, how do I fix this?

**Comment by NightfallChease** [comment]
nvm these commands fixed it.
thx for ur help
