### ISSUE TITLE
cl critical structure corruption BSOD

### ISSUE THREAD

**Issue by fwf02** [hfiref0x/KDU#34]
when using DSE 0 i got cl critical structure corruption bsod 20h2  OS Build 19042.804

**Comment by knewstimek** [comment]
Do you get BSOD as soon as you change DSE to 0?

**Comment by hfiref0x** [comment]
> when using DSE 0 i got cl critical structure corruption bsod 20h2 OS Build 19042.804

Sure why not. It is expected Windows reaction. What is your question here?

**Comment by fwf02** [comment]
> Do you get BSOD as soon as you change DSE to 0?

yes

**Comment by fwf02** [comment]
> > when using DSE 0 i got cl critical structure corruption bsod 20h2 OS Build 19042.804
> 
> Sure why not. It is expected Windows reaction. What is your question here?

is it supposed to be like that?

**Comment by hfiref0x** [comment]
You have corrupted critical Windows structure that is under PatchGuard supervision with a random time of check. Of course it can and will BSOD sometime.
