### ISSUE TITLE
Windows crashes after minutes after re-enable DSE

### ISSUE THREAD

**Issue by CycloneRing** [hfiref0x/KDU#40]
Hi, 
I use kdu -dse 0 to disable DSE and then I load my driver. (at first attempt it says current value is 16 and set to 0)
I use kdu -dse 6 to re-enable DSE just in less than 30 sec. (i tried -dse 16 but it set it to 10)
Everything works perfectly until after minutes system crashes with bluescreen.

Event Log says :
> The mrxsmb10 service failed to start due to the following error:  Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

mrxsmb10 is a unsigned driver from Microsoft itself. How can i avoid this?

_Also out of curiosity how those unsigned drivers are loaded by Microsoft at first place it's like 100+ drivers with not certificate in system32/drivers ?

**Comment by hfiref0x** [comment]
Hello,
>>I use kdu -dse 6 to re-enable DSE just in less than 30 sec. (i tried -dse 16 but it set it to 10)

DSE value is a combination of flags, if it was 16 then it must be restored to 16.
10 is a hexademical representation of decimal 16.

>>system crashes with bluescreen
What does it dispay to you? And what exactly event log entry looks like.

>>mrxsmb10 
It doesn't make any sense, Windows doesn't load unsigned drivers and this one is from Microsoft. The only possible scenario here is when this file is corrupted.

Run **sfc /verifyonly** from elevated command prompt. It will produce log Windows\Logs\CBS\CBS.log, search inside for this driver.

**Comment by CycloneRing** [comment]
Oh thanks I used hex and it's fine now.
