### ISSUE TITLE
Could not load drivers database, GetLastError 126

### ISSUE THREAD

**Issue by Sgamzat05** [hfiref0x/KDU#50]
![image](https://user-images.githubusercontent.com/46753195/210267684-193ec9e8-8ac6-4f40-bcae-b7ff598c6874.png)

**Comment by hfiref0x** [comment]
https://github.com/hfiref0x/KDU#build-and-notes

>Complete working binaries include: kdu.exe (main executable) and drv64.dll (drivers database). They must reside in the same directory that must have R/W access enabled for kdu.exe. All binaries MUST BE compiled in "Release" configuration.
