### ISSUE TITLE
BSOD with hyper-v turned on in Windows 11 22H2

### ISSUE THREAD

**Issue by felipejfc** [hfiref0x/KDU#55]
If I have hyper-v turned on:
```
bcdedit.exe /set hypervisorlaunchtype auto
```
provider 0 will BSOD on win11

If I turn hyper-v off it will work without problems:
```
bcdedit.exe /set hypervisorlaunchtype off
```

Is it possible to make it work with hyper-v launch?

**Comment by hfiref0x** [comment]
I'm not a developer of this driver what do you want from me?

**Comment by CycloneRing** [comment]
> I'm not a developer of this driver what do you want from me?

lol, I couldn't stop laughing reading this
