### ISSUE TITLE
Unable to load vulnerable driver, NTSTATUS (0xC0000603)

### ISSUE THREAD

**Issue by ShaggyLorean** [hfiref0x/KDU#60]
Simply, can't disable dse or can't map anything.
![image](https://user-images.githubusercontent.com/91439299/228092458-fe4a06d3-19be-4b38-a221-2b281f89c26c.png)

**Comment by hfiref0x** [comment]
And can't google that error code?
STATUS_IMAGE_CERT_REVOKED
