### ISSUE TITLE
vulnerable driver is already loaded

### ISSUE THREAD

**Issue by fwf02** [hfiref0x/KDU#61]
friend of mine cant load the driver but for me its work we use same windows version 22621.1413 windows 11

me

![Ct82PAPLSmGvnADSKgnXyQ](https://user-images.githubusercontent.com/27238585/228938569-3ef57007-1863-4d23-9c1b-bc4b4bc6486b.png)

friend 

![image](https://user-images.githubusercontent.com/27238585/228938626-868554a5-0f67-4882-9e72-ef0d96d99795.png)

what is the issue here?

**Comment by hfiref0x** [comment]
Hello,

he probably has installed MSI bundle called "afterburner" that loads it own RTCore of different version.
