### ISSUE TITLE
suggestion: add "patchguard dance" from wind

### ISSUE THREAD

**Issue by Jmpyyn** [hfiref0x/KDU#67]
would it be possible to add the "patchguard dance" from https://github.com/katlogic/WindowsD to prevent bsod after touching dse state?

**Comment by hfiref0x** [comment]
The "patchguard dance" in the above project is a trivial IAT hook on services.exe to achieve unknown goals as it makes absolutely no difference if you do the same patch_dse->NtLoadDriver->restore_dse in your app without using any kind of SCM (ffs why it even use it). In maybe will save you few milliseconds compared to running "kdu with dse off, loading your loader, running kdu dse on", but you will never know was it enough or PG already did the check. KDU will not patch (nor even touch) any memory of system processes.
