### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by ByteWhite1x1** [hfiref0x/KDU#73]
Hi.

Unless you're not already aware of https://github.com/ByteWhite1x1/EDR-bypass-disable-PspNotifyEnableMask

I also have DSE bypass at runtime for Windows 10/11 22H2. If you need. That's my thank you to for the KDU project. It's been really useful with testing. 

You just PM me or something if you want a private DSE bypass. As of 09/2023. MS has patched this in the latest Windows 10 Pro 22H2. You need to do the PTE trick to bypass DSE without a BSDO. I don't want to post this information publicly. It's only for those who work hard like you.

**Comment by hfiref0x** [comment]
Hello,

thanks for feedback.

This project is in public domain with all source code available under MIT license for everyone. I'm not interesting in any kind of "private" whatsoever stuff. Also I'm not interested in DSE bypasses of any kind, private or public.

If you are willing to share your code -> do it, you have entire github to host your code/ideas etc.
