### ISSUE TITLE
Cannot load drivers database, GetLastError 126:

### ISSUE THREAD

**Issue by Alexmalab** [hfiref0x/KDU#74]
[+] The "" hypervisor present
[!] Cannot load drivers database, GetLastError 126: [+] Return value: 0. Bye-bye!

**Comment by Alexmalab** [comment]
run .\kdu.exe -list
[#] Kernel Driver Utility v1.3.3 (build 2307) started, (c)2020 - 2023 KDU Project
[#] Built at Sat Sep  9 20:30:24 2023, header checksum 0x5C87C
[#] Supported x64 OS : Windows 7 and above
[*] CPU vendor string: GenuineIntel
[*] Windows version: 10.0 build 22621
[*] SecureBoot is disabled on this machine
[+] MSFT Driver block list is enabled
[!] Cannot load drivers database, GetLastError 126: [+] Return value: 1. Bye-bye!

**Comment by hfiref0x** [comment]
Duplicate https://github.com/hfiref0x/KDU/issues/50
