### ISSUE TITLE
Could not accept victim target, GetLastError 2148204812

### ISSUE THREAD

**Issue by takoda121** [hfiref0x/KDU#78]
On all providers it prints this error
![Image](https://github.com/hfiref0x/KDU/assets/77277659/736ee52a-d54a-4df9-a22b-e0494a66a23b)

**Comment by hfiref0x** [comment]
You excluded all useful information from your log. How do I suppose to answer you looking on HRESULT value which meaning you can google yourself?

**Comment by hfiref0x** [comment]
You are using outdated 1.2.8 version which uses Process Explorer 16.x driver. This driver has been baned by Microsoft which is clearly indicated by HRESULT 0x800B010C (A certificate was explicitly revoked by its issuer). Use a last version from this repository.

**Comment by takoda121** [comment]
works now ty
