### ISSUE TITLE
Randomly BSOD

### ISSUE THREAD

**Issue by Narumiii** [hfiref0x/KDU#8]
Hello hfiref0x i am testing with a weird issue let me explain. I have 2 computers both uses the same Windows 10 edition (Professional) and build (the latest) 19041.1023, on the first computer i don't get BSOD never but on the second i get BSOD after some minutes after modifiying CI.DLL value (i always restore the original value) the BSOD error code is CRITICAL_STRUCTURE_CORRUPTION - CI.DLL. This happened to me before i fixed it by reinstalling Windows with a the latest version via USB, its there any alternative to the reinstall? Thanks.

**Comment by hfiref0x** [comment]
This is expected BSOD from PatchGuard. You always play Russian roulette when modifying anything protected by PG. There is no workarounds and this is not an issue of of KDU.
