### ISSUE TITLE
cant use PsGetCreateProcessNotifyRoutine() ???

### ISSUE THREAD

**Issue by lastime1650** [hfiref0x/KDU#80]
i want to use that, but do not work anything..

**Comment by hfiref0x** [comment]
How does it related to this repository?

**Comment by lastime1650** [comment]
This function does not work. I made ioctl by implementing it as a missing iocreatedriver() function in DriverObject, but not work PsSetCreateNotifyRoutine() What's the problem? also RouteEX()  not used, the integrity option was excluded.

In other words, is there a way to write that routine function? The reason why I can't is because I thought it was KDU MAPPER.

**Comment by hfiref0x** [comment]
If your blaberry is about this API not working in a mapped driver, then why it should work at first place?

These API _PsGetCreateProcessNotifyRoutine_/_PsGetCreateProcessNotifyRoutineEx_ dumb empty routines which just passes control to _PspSetCreateProcessNotifyRoutine_ which inside validates callback address to be inside loaded modules list. 

Solution: find a codecave inside some legit loaded driver, write a jump to your callback inside it and pass this jump address as callback address to API.

Prior creating such "issues" without any kind of useful input do something on your own to not look like an idiot.
