### ISSUE TITLE
Providers table not found

### ISSUE THREAD

**Issue by xi4o7e** [hfiref0x/KDU#85]
![image](https://github.com/hfiref0x/KDU/assets/48150443/d8e9731c-799f-4d2c-829b-b626551a76fc)

**Comment by hfiref0x** [comment]
Your compiled drv64.dll is invalid.

**Comment by xi4o7e** [comment]
![image](https://github.com/hfiref0x/KDU/assets/48150443/48ee44d5-1d6d-4a16-b34d-7f8a1afe6dff)

1.4.0

**Comment by hfiref0x** [comment]
You didn't built it in Release. Your are running Debug version which is clearly stated on your screenshot.

**Comment by xi4o7e** [comment]
OK,thank you!
