### ISSUE TITLE
Heavy system load at target driver call

### ISSUE THREAD

**Issue by T-Troll** [hfiref0x/KDU#9]
Thanks for tool, it can help me to avoid stupid and non-free fingerprinting, but i need you help.

I write a tool to control fans/temps/power distribution for some specific hardware (specific manufacturer).
It uses kernel driver, so now it can only work in test mode.
I try to use your tool, and the current stage is:
- I can successfully load driver, initialization is OK.
- I can access driver trough IO, operation chain works as well.

The issue are - some IO operations provide heavy system load (interrupts catch 50-80% CPU).
They work, but took minutes to hour at so unresponsive system.

I'm out of ideas why it happened, direct loading didn't provide this issue.

PS: I access ACPI driver from mine, is this the source of the issue? How can I fix it?

**Comment by hfiref0x** [comment]
Purpose of the loader - inject your code to the kernel and run it. This is where KDU authority ends.
This is clearly not an issue of loader.
