### ISSUE TITLE
Use in Python

### ISSUE THREAD

**Issue by hapvlz** [hfiref0x/KDU#93]
Hey Guys,

I have python script that simply read memory of game. Unfortunately due to the antihack (Xigncode) once it load I'm not able to read any memory (getting access denied) even with debug mode.

Can the .dll from kdu.exe somehow be used in python code?
It works fine with CE and I can read memory, but how I can do it with python? 

Thank you! :)

**Comment by hapvlz** [comment]
What I've managed to do so far and somehow it works :D is - 

Add "wait for input" in python code (so I can have chance to inject DLL to python.exe process)
Inject DLL to python process
then it can read memory :D

I was trying to load the DLL directly in python code, but it's giving an error. 

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by hfiref0x** [comment]
How does it related to this repository? This is not a Python developers support board.
