### ISSUE TITLE
Driver import table parsing issue

### ISSUE THREAD

**Issue by zhutingxf** [hfiref0x/KDU#94]
The imported functions in the driver's import table include not only functions from ntoskrnl but also from hal. For instance, when my driver utilizes KeQueryPerformanceCounter, loading the driver results in a blue screen. Upon inspecting the code, it seems that the import table parsing is incomplete, as it does not resolve the dependencies from hal.

**Comment by hfiref0x** [comment]
It is not supposed to resolve anything that target driver want to import. This is by design and won't be changed.
