### ISSUE TITLE
add dse_pg bypass

### ISSUE THREAD

**Issue by noneof123** [hfiref0x/KDU#95]
see https://github.com/4l3x777/dse_pg_bypass

**Comment by hfiref0x** [comment]
Blatant copy-paste from KDU without giving any kind of credit. No, I won't add this copy-paste trash at all.

https://github.com/4l3x777/dse_pg_bypass/blob/main/includes/amd.h#L4-L32

https://github.com/4l3x777/dse_pg_bypass/blob/main/src/amd.cpp#L6-L60
