### ISSUE TITLE
windows 24h2

### ISSUE THREAD

**Issue by Whothatmofo** [hfiref0x/KDU#98]
can't seem to get it to work properly with windows 24h2 and cant load drivers.

**Comment by hfiref0x** [comment]
Very informative. Show kdu -diag.

**Comment by Whothatmofo** [comment]
![wefewr](https://github.com/user-attachments/assets/86350012-e7ae-4a33-b54c-41d1e1cd6bec)

**Comment by hfiref0x** [comment]
It cannot find internal CI.DLL variable. Attach your CI.DLL somewhere and post a link to it.

**Comment by Whothatmofo** [comment]
ci.dll from system32, correct

**Comment by Whothatmofo** [comment]
https://drive.google.com/file/d/1zs_ZttCD4Bj61bNl62hexPX7uGH4Nrv7/view?usp=drive_link

**Comment by hfiref0x** [comment]
Your link gives "Access denied".

**Comment by Whothatmofo** [comment]
try it now, sorry hfire

**Comment by hfiref0x** [comment]
Open dsefix.cpp and replace KDUpCheckInstructionBlock with

`ULONG KDUpCheckInstructionBlock(
    _In_ PBYTE Code,
    _In_ ULONG Offset
)
{
    ULONG offset = Offset;
    hde64s hs;

    RtlSecureZeroMemory(&hs, sizeof(hs));

    hde64_disasm(&Code[offset], &hs);
    if (hs.flags & F_ERROR)
        return 0;

    if (hs.len != 3)
        return 0;

    //
    // mov     r9, rbx
    //
    if (Code[offset] != 0x4C ||
        Code[offset + 1] != 0x8B)
    {
        return 0;
    }

    offset += hs.len;

    hde64_disasm(&Code[offset], &hs);
    if (hs.flags & F_ERROR)
        return 0;

    if (hs.len != 3)
        return 0;

    //
    // mov     r8, rdi 
    // 
    // or 
    //
    // mov     r8d, edi
    if (Code[offset] != 0x4C && 
        Code[offset] != 0x44 &&
        Code[offset + 1] != 0x8B)
    {
        return 0;
    }

    offset += hs.len;

    hde64_disasm(&Code[offset], &hs);
    if (hs.flags & F_ERROR)
        return 0;
    if (hs.len == 3) {

        //
        // mov     rdx, rsi
        //
        if (Code[offset] != 0x48 ||
            Code[offset + 1] != 0x8B)
        {
            return 0;
        }
    }
    else if (hs.len == 5)
    {
        //
        // mov[rsp + 38h + 28h], rax
        //
        if (Code[offset] != 0x48 ||
            Code[offset + 1] != 0x89)
        {
            return 0;
        }

        offset += hs.len;
        hde64_disasm(&Code[offset], &hs);
        if (hs.flags & F_ERROR || hs.len != 3) {
            return 0;
        }
        //
        // mov     rdx, rsi
        //
        if (Code[offset] != 0x48 ||
            Code[offset + 1] != 0x8B)
        {
            return 0;
        }
    }
    else
        return 0;

    offset += hs.len;

    hde64_disasm(&Code[offset], &hs);
    if (hs.flags & F_ERROR)
        return 0;

    if (hs.len != 2)
        return 0;

    //
    // mov     ecx, ebp
    //
    if (Code[offset] != 0x8B ||
        Code[offset + 1] != 0xCD)
    {
        return 0;
    }

    return offset + hs.len;
}`

Tell me if it works.

**Comment by Whothatmofo** [comment]
will update you soon as i can
